### PR TITLE
Create dependency-review.yml

### PR DESCRIPTION
**Pull request by coliff**
REF: https://github.com/actions/dependency-review-action#dependency-review-action

### CODE REVIEW

**Comment by msankaran0712** [comment]
@coliff is this not already taken care of by dependabot security alerts?

**Comment by coliff** [comment]
> @coliff is this not already taken care of by dependabot security alerts?

sort of... but dependabot security alerts runs on our EXISTING codebase. This GitHub Action runs on any Pull Requests so could potentially catch issues before it is merged.

Honestly, it's unlikely it'll catch anything but I want to add tests for everything to make the codebase bulletproof and 100% error-free. :-)

**Comment by msankaran0712** [comment]
> > @coliff is this not already taken care of by dependabot security alerts?
> 
> sort of... but dependabot security alerts runs on our **EXISTING** codebase. This GitHub Action runs on any Pull Requests so could potentially catch issues **BEFORE** it is merged.
> 
> Honestly, it's unlikely it'll catch anything but I want to add tests for everything to make the codebase bulletproof and 100% error-free. :-)

I feel dependabot is sufficient for now as it scans our codebase anyway.

**Comment by coliff** [comment]
There isn't a downside to including this though - and it doesn't cost anything. It makes this potentially safer for a project which is open-source. We're including it on all the other open-source projects we have.

**Comment by msankaran0712** [comment]
> > @coliff is this not already taken care of by dependabot security alerts?
> 
> sort of... but dependabot security alerts runs on our **EXISTING** codebase. This GitHub Action runs on any Pull Requests so could potentially catch issues **BEFORE** it is merged.
> 
> Honestly, it's unlikely it'll catch anything but I want to add tests for everything to make the codebase bulletproof and 100% error-free. :-)

how do we verify that dependency-review-action doesn't cause any security issues?

**Comment by coliff** [comment]
> how do we verify that dependency-review-action which is an open source doesn't cause any security issues?

it has read-only permission:

```yml
permissions:
  contents: read
```

...and it's created and maintained by GitHub.
https://github.com/actions?type=source

**Review by msankaran0712 — APPROVED** [review]

**Pull request merged**
